// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Lobby = __t.object("Lobby", {
  lobbyCode: __t.string(),
  lobbyName: __t.string(),
  ownerId: __t.identity(),
  isPublic: __t.bool(),
});
export type Lobby = __Infer<typeof Lobby>;

export const Player = __t.object("Player", {
  playerId: __t.u64(),
  lobbyCode: __t.string(),
  clientId: __t.identity(),
  name: __t.string(),
  score: __t.i32(),
});
export type Player = __Infer<typeof Player>;

export const User = __t.object("User", {
  identity: __t.identity(),
  name: __t.string(),
});
export type User = __Infer<typeof User>;

