// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import CreateLobbyReducer from "../create_lobby_reducer";
import JoinLobbyReducer from "../join_lobby_reducer";
import RemovePlayerReducer from "../remove_player_reducer";
import UpdateScoreReducer from "../update_score_reducer";
import UpdateUserNameReducer from "../update_user_name_reducer";

export type CreateLobbyParams = __Infer<typeof CreateLobbyReducer>;
export type JoinLobbyParams = __Infer<typeof JoinLobbyReducer>;
export type RemovePlayerParams = __Infer<typeof RemovePlayerReducer>;
export type UpdateScoreParams = __Infer<typeof UpdateScoreReducer>;
export type UpdateUserNameParams = __Infer<typeof UpdateUserNameReducer>;

