// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CreateLobbyArgs {
    pub user_name: String,
    pub code_arg: String,
}

impl From<CreateLobbyArgs> for super::Reducer {
    fn from(args: CreateLobbyArgs) -> Self {
        Self::CreateLobby {
            user_name: args.user_name,
            code_arg: args.code_arg,
        }
    }
}

impl __sdk::InModule for CreateLobbyArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `create_lobby`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait create_lobby {
    /// Request that the remote module invoke the reducer `create_lobby` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`create_lobby:create_lobby_then`] to run a callback after the reducer completes.
    fn create_lobby(&self, user_name: String, code_arg: String) -> __sdk::Result<()> {
        self.create_lobby_then(user_name, code_arg, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `create_lobby` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn create_lobby_then(
        &self,
        user_name: String,
        code_arg: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl create_lobby for super::RemoteReducers {
    fn create_lobby_then(
        &self,
        user_name: String,
        code_arg: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            CreateLobbyArgs {
                user_name,
                code_arg,
            },
            callback,
        )
    }
}
