// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Lobby {
    pub lobby_code: String,
    pub owner_id: __sdk::Identity,
}

impl __sdk::InModule for Lobby {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Lobby`.
///
/// Provides typed access to columns for query building.
pub struct LobbyCols {
    pub lobby_code: __sdk::__query_builder::Col<Lobby, String>,
    pub owner_id: __sdk::__query_builder::Col<Lobby, __sdk::Identity>,
}

impl __sdk::__query_builder::HasCols for Lobby {
    type Cols = LobbyCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        LobbyCols {
            lobby_code: __sdk::__query_builder::Col::new(table_name, "lobby_code"),
            owner_id: __sdk::__query_builder::Col::new(table_name, "owner_id"),
        }
    }
}

/// Indexed column accessor struct for the table `Lobby`.
///
/// Provides typed access to indexed columns for query building.
pub struct LobbyIxCols {
    pub lobby_code: __sdk::__query_builder::IxCol<Lobby, String>,
}

impl __sdk::__query_builder::HasIxCols for Lobby {
    type IxCols = LobbyIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        LobbyIxCols {
            lobby_code: __sdk::__query_builder::IxCol::new(table_name, "lobby_code"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Lobby {}
