// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Player {
    pub player_id: u64,
    pub lobby_code: String,
    pub client_id: __sdk::Identity,
    pub name: String,
    pub score: i32,
}

impl __sdk::InModule for Player {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Player`.
///
/// Provides typed access to columns for query building.
pub struct PlayerCols {
    pub player_id: __sdk::__query_builder::Col<Player, u64>,
    pub lobby_code: __sdk::__query_builder::Col<Player, String>,
    pub client_id: __sdk::__query_builder::Col<Player, __sdk::Identity>,
    pub name: __sdk::__query_builder::Col<Player, String>,
    pub score: __sdk::__query_builder::Col<Player, i32>,
}

impl __sdk::__query_builder::HasCols for Player {
    type Cols = PlayerCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PlayerCols {
            player_id: __sdk::__query_builder::Col::new(table_name, "player_id"),
            lobby_code: __sdk::__query_builder::Col::new(table_name, "lobby_code"),
            client_id: __sdk::__query_builder::Col::new(table_name, "client_id"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            score: __sdk::__query_builder::Col::new(table_name, "score"),
        }
    }
}

/// Indexed column accessor struct for the table `Player`.
///
/// Provides typed access to indexed columns for query building.
pub struct PlayerIxCols {
    pub lobby_code: __sdk::__query_builder::IxCol<Player, String>,
    pub player_id: __sdk::__query_builder::IxCol<Player, u64>,
}

impl __sdk::__query_builder::HasIxCols for Player {
    type IxCols = PlayerIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PlayerIxCols {
            lobby_code: __sdk::__query_builder::IxCol::new(table_name, "lobby_code"),
            player_id: __sdk::__query_builder::IxCol::new(table_name, "player_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Player {}
