// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateUserNameArgs {
    pub name: String,
}

impl From<UpdateUserNameArgs> for super::Reducer {
    fn from(args: UpdateUserNameArgs) -> Self {
        Self::UpdateUserName { name: args.name }
    }
}

impl __sdk::InModule for UpdateUserNameArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_user_name`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_user_name {
    /// Request that the remote module invoke the reducer `update_user_name` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`update_user_name:update_user_name_then`] to run a callback after the reducer completes.
    fn update_user_name(&self, name: String) -> __sdk::Result<()> {
        self.update_user_name_then(name, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `update_user_name` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn update_user_name_then(
        &self,
        name: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl update_user_name for super::RemoteReducers {
    fn update_user_name_then(
        &self,
        name: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(UpdateUserNameArgs { name }, callback)
    }
}
