// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateScoreArgs {
    pub player_id: u64,
    pub new_score: i32,
}

impl From<UpdateScoreArgs> for super::Reducer {
    fn from(args: UpdateScoreArgs) -> Self {
        Self::UpdateScore {
            player_id: args.player_id,
            new_score: args.new_score,
        }
    }
}

impl __sdk::InModule for UpdateScoreArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_score`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_score {
    /// Request that the remote module invoke the reducer `update_score` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`update_score:update_score_then`] to run a callback after the reducer completes.
    fn update_score(&self, player_id: u64, new_score: i32) -> __sdk::Result<()> {
        self.update_score_then(player_id, new_score, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `update_score` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn update_score_then(
        &self,
        player_id: u64,
        new_score: i32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl update_score for super::RemoteReducers {
    fn update_score_then(
        &self,
        player_id: u64,
        new_score: i32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            UpdateScoreArgs {
                player_id,
                new_score,
            },
            callback,
        )
    }
}
